/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author yuliaananta
 */
public class Barang extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        SelectBarang();
        SelectJenis();
        GetJenis();
        
    }
    
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JenisKat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        HargaBarang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AddBarang = new javax.swing.JButton();
        UpdateBarang = new javax.swing.JButton();
        DeleteBarang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BarangTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        StokBarang = new javax.swing.JTextField();
        IdBarang = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        MerkKat = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        IdKat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JenisTable = new javax.swing.JTable();
        AddKat = new javax.swing.JButton();
        UpdateKat = new javax.swing.JButton();
        DeleteKat = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JumlahBarang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        JenisCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Master");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Kasir");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Pembeli");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data Barang");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transaksi");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Laporan");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\master data.png")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Transaksi.png")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Laporan.png")); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Log Out.png")); // NOI18N

        jLabel25.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Log Out");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Logo Putih.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(3, 3, 3))))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25)))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Kategori");

        jLabel12.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("ID");

        JenisKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKatActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Nama");

        jLabel15.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Harga");

        jLabel16.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Jenis");

        AddBarang.setBackground(new java.awt.Color(0, 102, 102));
        AddBarang.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        AddBarang.setForeground(new java.awt.Color(255, 255, 255));
        AddBarang.setText("Insert");
        AddBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBarangMouseClicked(evt);
            }
        });
        AddBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBarangActionPerformed(evt);
            }
        });

        UpdateBarang.setBackground(new java.awt.Color(0, 102, 102));
        UpdateBarang.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        UpdateBarang.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBarang.setText("Update");
        UpdateBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBarangMouseClicked(evt);
            }
        });
        UpdateBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBarangActionPerformed(evt);
            }
        });

        DeleteBarang.setBackground(new java.awt.Color(0, 102, 102));
        DeleteBarang.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        DeleteBarang.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBarang.setText("Delete");
        DeleteBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBarangMouseClicked(evt);
            }
        });
        DeleteBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBarangActionPerformed(evt);
            }
        });

        BarangTable.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        BarangTable.setForeground(new java.awt.Color(0, 102, 102));
        BarangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Harga", "Stok", "Satuan", "Jenis"
            }
        ));
        BarangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarangTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BarangTable);

        jLabel17.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Stok");

        jLabel18.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Merk");

        MerkKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MerkKatActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("ID");

        IdKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdKatActionPerformed(evt);
            }
        });

        JenisTable.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        JenisTable.setForeground(new java.awt.Color(0, 102, 102));
        JenisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Merk"
            }
        ));
        JenisTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JenisTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JenisTable);

        AddKat.setBackground(new java.awt.Color(0, 102, 102));
        AddKat.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        AddKat.setForeground(new java.awt.Color(255, 255, 255));
        AddKat.setText("Insert");
        AddKat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddKatMouseClicked(evt);
            }
        });
        AddKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddKatActionPerformed(evt);
            }
        });

        UpdateKat.setBackground(new java.awt.Color(0, 102, 102));
        UpdateKat.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        UpdateKat.setForeground(new java.awt.Color(255, 255, 255));
        UpdateKat.setText("Update");
        UpdateKat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateKatMouseClicked(evt);
            }
        });
        UpdateKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateKatActionPerformed(evt);
            }
        });

        DeleteKat.setBackground(new java.awt.Color(0, 102, 102));
        DeleteKat.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        DeleteKat.setForeground(new java.awt.Color(255, 255, 255));
        DeleteKat.setText("Delete");
        DeleteKat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteKatMouseClicked(evt);
            }
        });
        DeleteKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteKatActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Data Barang");

        jLabel19.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Satuan");

        jLabel21.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Jenis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JenisKat)
                                    .addComponent(MerkKat)
                                    .addComponent(IdKat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AddKat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UpdateKat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DeleteKat))
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addGap(25, 25, 25))
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel12))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(23, 23, 23)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(HargaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(NamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(IdBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(StokBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(JumlahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(JenisCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddBarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpdateBarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DeleteBarang))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(587, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(362, 362, 362)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(IdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(JumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddBarang)
                        .addComponent(UpdateBarang)
                        .addComponent(DeleteBarang))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(JenisCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(IdKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JenisKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MerkKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddKat)
                            .addComponent(UpdateKat)
                            .addComponent(DeleteKat))))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel14)
                    .addContainerGap(601, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void SelectBarang(){
        try{
          Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
          St = Con.createStatement();
          Rs = St.executeQuery("select * from barang");
          BarangTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e){
          e.printStackTrace();  
        } 
    }
    
    public void SelectJenis(){
        try{
          Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
          St = Con.createStatement();
          Rs = St.executeQuery("select * from jenisbarang");
          JenisTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e){
          e.printStackTrace();  
        } 
    }
    
    public void GetJenis(){
        try{
       Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
       St = Con.createStatement();
       String query = "select*from koperasi.jenisbarang";
       Rs = St.executeQuery(query);
       while(Rs.next()){
           String MyCat = Rs.getString("JENIS_BARANG");
           JenisCb.addItem(MyCat);
       }
    }catch(Exception e){
        
    }

    }


    
    private void AddBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBarangActionPerformed

    private void UpdateBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBarangActionPerformed

    private void DeleteBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBarangActionPerformed

    private void JenisKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisKatActionPerformed

    private void MerkKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MerkKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MerkKatActionPerformed

    private void IdKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdKatActionPerformed

    private void AddKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddKatActionPerformed

    private void UpdateKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateKatActionPerformed

    private void DeleteKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteKatActionPerformed

    private void AddBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBarangMouseClicked
        // TODO add your handling code here:
        try{
           Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
           PreparedStatement add = Con.prepareStatement("insert into barang values (?,?,?,?,?,?)");
           add.setString(1, IdBarang.getText());
           add.setString(2, NamaBarang.getText());
           add.setDouble(3, Double.valueOf(HargaBarang.getText()));
           add.setInt(4, Integer.valueOf(StokBarang.getText()));
           add.setString(5, JumlahBarang.getText());
           add.setString(6, JenisCb.getSelectedItem().toString());
           int row = add.executeUpdate();
           JOptionPane.showMessageDialog(this,"Product Successfully Added");
           Con.close();
           SelectBarang();
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_AddBarangMouseClicked

    private void UpdateBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBarangMouseClicked
        // TODO add your handling code here:
        if(IdBarang.getText().isEmpty() || NamaBarang.getText().isEmpty() || HargaBarang.getText().isEmpty()|| StokBarang.getText().isEmpty()||JumlahBarang.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Missing Information"); 
        }else{
            try{
              Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
              String UpdateQuery = "Update koperasi.barang set NM_BARANG='" + NamaBarang.getText()+ "'" + ", HARGA_BARANG='" + HargaBarang.getText()+"'"+",STOK_BARANG='"+StokBarang.getText()+"'"+", JML_BARANG='"+JumlahBarang.getText()+"'"+"where ID_BARANG='" + IdBarang.getText()+"'";
              Statement Add = Con.createStatement();
              Add.execute(UpdateQuery);
              JOptionPane.showMessageDialog(this, "Product Updated Succesfully");
              SelectBarang();
            }catch(SQLException e) {
               e.printStackTrace(); 
            }
        }
            
    }//GEN-LAST:event_UpdateBarangMouseClicked

    private void DeleteBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBarangMouseClicked
        // TODO add your handling code here:  
        if(IdBarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter The Product to be Deleted");
        }else{
            try{
              Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
              String Id = IdBarang.getText();
              String Query = "Delete from koperasi.barang where ID_BARANG='" + Id+"'";
              Statement Add = Con.createStatement();
              Add.executeUpdate(Query);
              SelectBarang();
              JOptionPane.showMessageDialog(this, "Product Deleted Succesfully");
            }catch(SQLException e){
                e.printStackTrace(); 
            }
        }
        
        
    }//GEN-LAST:event_DeleteBarangMouseClicked

    private void BarangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)BarangTable.getModel();
        int Myindex = BarangTable.getSelectedRow();
        IdBarang.setText(model.getValueAt(Myindex, 0).toString());
        NamaBarang.setText(model.getValueAt(Myindex, 1).toString());
        HargaBarang.setText(model.getValueAt(Myindex, 2).toString());
        StokBarang.setText(model.getValueAt(Myindex, 3).toString());
        JumlahBarang.setText(model.getValueAt(Myindex, 4).toString());

    }//GEN-LAST:event_BarangTableMouseClicked

    private void AddKatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddKatMouseClicked
        // TODO add your handling code here:
        try{
           Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
           PreparedStatement add = Con.prepareStatement("insert into jenisbarang values (?,?,?)");
           add.setString(1, IdKat.getText());
           add.setString(2, JenisKat.getText());
           add.setString(3, MerkKat.getText());
           int row = add.executeUpdate();
           JOptionPane.showMessageDialog(this,"Product type Successfully Added");
           Con.close();
           SelectJenis();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddKatMouseClicked

    private void UpdateKatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateKatMouseClicked
        // TODO add your handling code here:
        if(IdKat.getText().isEmpty() || JenisKat.getText().isEmpty() || MerkKat.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Missing Information"); 
        }else{
            try{
              Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
              String UpdateQuery = "Update koperasi.jenisbarang set JENIS_BARANG='" + JenisKat.getText()+ "'" + ", MERK_BARANG='" + MerkKat.getText()+"'"+"where ID_BARANG='" + IdKat.getText()+"'";
              Statement Add = Con.createStatement();
              Add.execute(UpdateQuery);
              JOptionPane.showMessageDialog(this, "Product type Updated Succesfully");
              SelectJenis();
            }catch(SQLException e) {
               e.printStackTrace(); 
            }
        }
            
    }//GEN-LAST:event_UpdateKatMouseClicked

    private void DeleteKatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteKatMouseClicked
        // TODO add your handling code here:
        if(IdKat.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter The Product type to be Deleted");
        }else{
            try{
              Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
              String Id = IdKat.getText();
              String Query = "Delete from koperasi.jenisbarang where ID_BARANG= " + Id;
              Statement Add = Con.createStatement();
              Add.executeUpdate(Query);
              SelectJenis();
              JOptionPane.showMessageDialog(this, "Product type Deleted Succesfully");
            }catch(SQLException e){
                e.printStackTrace(); 
            }
        }
    }//GEN-LAST:event_DeleteKatMouseClicked

    private void JenisTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JenisTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)JenisTable.getModel();
        int Myindex = JenisTable.getSelectedRow();
        IdKat.setText(model.getValueAt(Myindex, 0).toString());
        JenisKat.setText(model.getValueAt(Myindex, 1).toString());
        MerkKat.setText(model.getValueAt(Myindex, 2).toString());
        
    }//GEN-LAST:event_JenisTableMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new Order().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Pembeli().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new Kasir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBarang;
    private javax.swing.JButton AddKat;
    private javax.swing.JTable BarangTable;
    private javax.swing.JButton DeleteBarang;
    private javax.swing.JButton DeleteKat;
    private javax.swing.JTextField HargaBarang;
    private javax.swing.JTextField IdBarang;
    private javax.swing.JTextField IdKat;
    private javax.swing.JComboBox<String> JenisCb;
    private javax.swing.JTextField JenisKat;
    private javax.swing.JTable JenisTable;
    private javax.swing.JTextField JumlahBarang;
    private javax.swing.JTextField MerkKat;
    private javax.swing.JTextField NamaBarang;
    private javax.swing.JTextField StokBarang;
    private javax.swing.JButton UpdateBarang;
    private javax.swing.JButton UpdateKat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
