/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasi;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
//import org.apache.log4j.Logger;
//import org.apache.log4j.Priority;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author yuliaananta
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        SelectBarang();
        SelectPembeli();
        //update();
        GetToday();
        GetPay();
        GetKasir();
        GetPembeli();
        
    }
    
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DataKasir = new javax.swing.JLabel();
        DataPembeli = new javax.swing.JLabel();
        DataBarang = new javax.swing.JLabel();
        Order = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        NamaPembelilbl = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BillId = new javax.swing.JTextField();
        PaymethodCb = new javax.swing.JComboBox<>();
        Qtytb = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        AddToBtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        TotalPembayaranlbl = new javax.swing.JLabel();
        AddOrderBtn = new javax.swing.JButton();
        PrintBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BayarTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        PembeliTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        BarangTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        IdKasirCb = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        IdPembeliCb = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JLabel();
        txtFieldBayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Master");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order");

        DataKasir.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        DataKasir.setForeground(new java.awt.Color(255, 255, 255));
        DataKasir.setText("Data Kasir");
        DataKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataKasirMouseClicked(evt);
            }
        });

        DataPembeli.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        DataPembeli.setForeground(new java.awt.Color(255, 255, 255));
        DataPembeli.setText("Data Pembeli");
        DataPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataPembeliMouseClicked(evt);
            }
        });

        DataBarang.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        DataBarang.setForeground(new java.awt.Color(255, 255, 255));
        DataBarang.setText("Data Barang");
        DataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataBarangMouseClicked(evt);
            }
        });

        Order.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Order.setForeground(new java.awt.Color(255, 255, 255));
        Order.setText("Transaksi");
        Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Laporan");

        jLabel25.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Log Out");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Logo Putih.png")); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\master data.png")); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Transaksi.png")); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Laporan.png")); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\yuliaananta\\Downloads\\Asset Koperasi\\Icon Home Page\\Log Out.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(133, 133, 133)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataPembeli)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DataKasir))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DataBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel32))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel25)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jSeparator4)))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)))
                .addComponent(DataKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(DataPembeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel30)
                        .addGap(9, 9, 9)))
                .addComponent(Order)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel25))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)))
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(265, 265, 265)
                .addComponent(jLabel11)
                .addGap(45, 45, 45)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Data Pembeli");

        jLabel12.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Nama Pembeli");

        jLabel13.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("ID Penjualan");

        jLabel15.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Jenis Pembayaran");

        jLabel17.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Jumlah Barang");

        jLabel18.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Harga");

        jLabel19.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Tanggal Pembayaran");

        NamaPembelilbl.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        NamaPembelilbl.setForeground(new java.awt.Color(0, 102, 102));
        NamaPembelilbl.setText("NamaPembeli");

        Datelbl.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Datelbl.setForeground(new java.awt.Color(0, 102, 102));
        Datelbl.setText("TanggalPembayaran");

        jLabel16.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Transaksi");

        jLabel21.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Data Barang");

        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });

        AddToBtn.setBackground(new java.awt.Color(0, 102, 102));
        AddToBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        AddToBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddToBtn.setText("Add To Order");
        AddToBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddToBtnMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Rp");

        TotalPembayaranlbl.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        TotalPembayaranlbl.setForeground(new java.awt.Color(0, 102, 102));
        TotalPembayaranlbl.setText("TotalPembayaran");

        AddOrderBtn.setBackground(new java.awt.Color(0, 102, 102));
        AddOrderBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        AddOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddOrderBtn.setText("Add Order");
        AddOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddOrderBtnMouseClicked(evt);
            }
        });

        PrintBtn.setBackground(new java.awt.Color(0, 102, 102));
        PrintBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        PrintBtn.setForeground(new java.awt.Color(255, 255, 255));
        PrintBtn.setText("Print");
        PrintBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintBtnMouseClicked(evt);
            }
        });

        BayarTbl.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        BayarTbl.setForeground(new java.awt.Color(0, 102, 102));
        BayarTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Penjualan", "Barang", "Jumlah Barang", "Harga Satuan", "Total Bayar", "Jenis Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(BayarTbl);

        PembeliTable.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        PembeliTable.setForeground(new java.awt.Color(0, 102, 102));
        PembeliTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "No Telepon", "Alamat"
            }
        ));
        PembeliTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PembeliTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PembeliTable);

        BarangTable.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        BarangTable.setForeground(new java.awt.Color(0, 102, 102));
        BarangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Harga", "Stok", "Satuan", "Jenis"
            }
        ));
        BarangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarangTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(BarangTable);

        jLabel14.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("ID Kasir");

        jLabel20.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("ID Pembeli");

        jLabel26.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("Bayar");

        jLabel27.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("Kembalian");

        Kembalian.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Kembalian.setEnabled(false);

        txtFieldBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldBayarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Qtytb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(AddToBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(372, 372, 372)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(TotalPembayaranlbl)
                                .addGap(47, 47, 47)
                                .addComponent(AddOrderBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrintBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NamaPembelilbl)
                                    .addComponent(BillId)
                                    .addComponent(PaymethodCb, 0, 149, Short.MAX_VALUE)
                                    .addComponent(Datelbl)
                                    .addComponent(IdPembeliCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel26))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(IdKasirCb, 0, 190, Short.MAX_VALUE)
                                            .addComponent(txtFieldBayar)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(220, 220, 220))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(618, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(371, 371, 371)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(BillId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(IdKasirCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(IdPembeliCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addComponent(txtFieldBayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(NamaPembelilbl)
                        .addComponent(jLabel27))
                    .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(PaymethodCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Datelbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddToBtn)
                    .addComponent(Qtytb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(TotalPembayaranlbl)
                    .addComponent(AddOrderBtn)
                    .addComponent(PrintBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel16)
                    .addContainerGap(771, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void SelectBarang(){
        try{
          Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
          St = Con.createStatement();
          Rs = St.executeQuery("select * from barang");
          BarangTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e){
          e.printStackTrace();  
        } 
    }
    
    public void SelectPembeli(){
        try{
           Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root",""); 
           St = Con.createStatement();
           Rs = St.executeQuery("select * from pembeli");
           PembeliTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private void GetToday(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        Datelbl.setText(dtf.format(now));
    }
    
    private void update(){
    int newqty = oldqty -  Integer.valueOf(Qtytb.getText());
    try{
              Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
              String UpdateQuery = "Update koperasi.barang set STOK_BARANG='" + newqty+"'"+"where ID_BARANG='" +IdBarang+"'";
              Statement Add = Con.createStatement();
              Add.execute(UpdateQuery);
             // JOptionPane.showMessageDialog(this, "Category Updated Succesfully");
              SelectBarang();
            }catch(SQLException e) {
               e.printStackTrace(); 
            }
    }
    
    private void GetPay(){
    try{
       Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
       St = Con.createStatement();
       String query = "select*from koperasi.pembayaran";
       Rs = St.executeQuery(query);
       while(Rs.next()){
           String MyPay = Rs.getString("ID_PEM");
           PaymethodCb.addItem(MyPay);
       }
    }catch(Exception e){
        
    }
}
    
    private void GetKasir(){
    try{
       Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
       St = Con.createStatement();
       String query = "select*from koperasi.kasir";
       Rs = St.executeQuery(query);
       while(Rs.next()){
           String Id = Rs.getString("ID_KASIR");
           IdKasirCb.addItem(Id);
       }
    }catch(Exception e){
        
    }
}
    
    private void GetPembeli(){
    try{
       Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
       St = Con.createStatement();
       String query = "select*from koperasi.pembeli";
       Rs = St.executeQuery(query);
       while(Rs.next()){
           String Id = Rs.getString("ID_PEMBELI");
           IdPembeliCb.addItem(Id);
       }
    }catch(Exception e){
        
    }
}
    
     
    
    private void PembeliTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PembeliTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)PembeliTable.getModel();
        int Myindex = PembeliTable.getSelectedRow();
        NamaPembelilbl.setText(model.getValueAt(Myindex, 1).toString());
//        IdPembeli.setText(model.getValueAt(Myindex, 0).toString());
//        NamaPembeli.setText(model.getValueAt(Myindex, 1).toString());
//        TelponPembeli.setText(model.getValueAt(Myindex, 2).toString());
//        AlamatPembeli.setText(model.getValueAt(Myindex, 3).toString());

        
    }//GEN-LAST:event_PembeliTableMouseClicked
int flag = 0, oldqty;
String IdBarang;
    private void BarangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)BarangTable.getModel();
        int Myindex = BarangTable.getSelectedRow();
        IdBarang = model.getValueAt(Myindex, 0).toString();
        //IdBarang = Integer.valueOf(model.getValueAt(Myindex, 0).toString());
        NamaBarang = model.getValueAt(Myindex, 1).toString();
//        IdBarang.setText(model.getValueAt(Myindex, 0).toString());
//        NamaBarang.setText(model.getValueAt(Myindex, 1).toString());
//        HargaBarang.setText(model.getValueAt(Myindex, 2).toString());
//        StokBarang.setText(model.getValueAt(Myindex, 3).toString());
        oldqty = Integer.valueOf(model.getValueAt(Myindex, 3).toString());
        flag =1;

    }//GEN-LAST:event_BarangTableMouseClicked
int i =1,Uprice,tot=0,total;
String NamaBarang;
    private void AddToBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddToBtnMouseClicked
        // TODO add your handling code here:
        if (flag == 0 || Price.getText().isEmpty()||Qtytb.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Select Product and enter Qty"); 
        }else{
            Uprice = Integer.valueOf(Price.getText());
            Vector v = new Vector();
            tot = Uprice * Integer.valueOf(Qtytb.getText());
            v.add(String.valueOf(i));
            //v.add(i);
            v.add(NamaBarang);
            v.add(Qtytb.getText());
            v.add(String.valueOf(Uprice));
            v.add(String.valueOf(tot));
            v.add(String.valueOf(PaymethodCb.getSelectedItem()));
           // v.add(Price.getText());


            DefaultTableModel dt = (DefaultTableModel) BayarTbl.getModel();
            dt.addRow(v);
            total = total+tot;
            TotalPembayaranlbl.setText(""+total);
            update();
            i++; 
        }
        
    }//GEN-LAST:event_AddToBtnMouseClicked

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void AddOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddOrderBtnMouseClicked
        // TODO add your handling code here:
        if(BillId.getText().isEmpty()){
           JOptionPane.showMessageDialog(this,"Enter the bill Id");  
        }else{
            
        }
        
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi","root","");
            PreparedStatement add = Con.prepareStatement("insert into penjualan values (?,?,?,?,?,?)");
            add.setString(PROPERTIES, NamaBarang);
            //add.setString(1, NamaPembelilbl.getText());
            add.setString(1, IdPembeliCb.getSelectedItem().toString());
            add.setInt(2, Integer.valueOf(BillId.getText()));
            add.setString(3, IdKasirCb.getSelectedItem().toString());
            add.setString(4, PaymethodCb.getSelectedItem().toString());
            add.setString(5, Datelbl.getText());
            add.setInt(6, Integer.valueOf(TotalPembayaranlbl.getText()));
            //add.setString(7, NamaPembelilbl.getText());
            
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Order Successfully Added");
            Con.close();
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddOrderBtnMouseClicked

    private void PrintBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintBtnMouseClicked
        // TODO add your handling code here:
        /*
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report.jesper"),null,koperasi.database.ConnectionHelper.getConnection());
            JasperViewer.viewReport(jp);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        */
        
        try{
            HashMap parameter = new HashMap();
            parameter.put("Tanggal", Datelbl.getText());
            parameter.put("Tunai", txtFieldBayar.getText());
            parameter.put("Kembali", Kembalian.getText());
            File jasperFile = new File("src/koperasi/strukOrder.jasper");
            JasperPrint jprint = JasperFillManager.fillReport(jasperFile.getPath(),parameter ,new JRTableModelDataSource(BayarTbl.getModel()));
            JasperViewer.viewReport(jprint,false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_PrintBtnMouseClicked

    private void DataKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataKasirMouseClicked
        // TODO add your handling code here:
        new Kasir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DataKasirMouseClicked

    private void DataPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPembeliMouseClicked
        // TODO add your handling code here:
        new Pembeli().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DataPembeliMouseClicked

    private void DataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBarangMouseClicked
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DataBarangMouseClicked

    private void OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMouseClicked
        // TODO add your handling code here:
        new Order().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrderMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel25MouseClicked

    private void txtFieldBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldBayarKeyPressed
        // TODO add your handling code here:
		if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
			if (! TotalPembayaranlbl.getText().equals("TotalPembayaran")) {
				int TotalHarga,TotalBayar,Kembali;
				TotalHarga = Integer.valueOf(TotalPembayaranlbl.getText());
				TotalBayar = Integer.valueOf(txtFieldBayar.getText());
				
				if(TotalHarga > TotalBayar){
					JOptionPane.showMessageDialog(this,"Money is not enough"); 
				} else{
					Kembali = TotalBayar -TotalHarga;
					Kembalian.setText(String.valueOf(Kembali));
				}
			} else {
				JOptionPane.showMessageDialog(this,"Belum ada order"); 
			}

		}
    }//GEN-LAST:event_txtFieldBayarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrderBtn;
    private javax.swing.JButton AddToBtn;
    private javax.swing.JTable BarangTable;
    private javax.swing.JTable BayarTbl;
    private javax.swing.JTextField BillId;
    private javax.swing.JLabel DataBarang;
    private javax.swing.JLabel DataKasir;
    private javax.swing.JLabel DataPembeli;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JComboBox<String> IdKasirCb;
    private javax.swing.JComboBox<String> IdPembeliCb;
    private javax.swing.JLabel Kembalian;
    private javax.swing.JLabel NamaPembelilbl;
    private javax.swing.JLabel Order;
    private javax.swing.JComboBox<String> PaymethodCb;
    private javax.swing.JTable PembeliTable;
    private javax.swing.JTextField Price;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JTextField Qtytb;
    private javax.swing.JLabel TotalPembayaranlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtFieldBayar;
    // End of variables declaration//GEN-END:variables
}
