/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yulia.ui;

//import com.yulia.database.BukuDatasource;
import datamanagerbuku.database.BukuDatasource;
import datamanagerbuku.models.Buku;
import datamanagerbuku.models.Buku;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author yuliaananta
 */
public class FormBukuActivity extends javax.swing.JFrame {

    /**
     * Creates new form FormBukuActivity
     */
    public FormBukuActivity() {
        initComponents();
    }
    
    private Buku buku;
    
    private void showError(String message){
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void showSucceed(String message){
        JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void showOldDataOf(Buku buku){
        judulField.setText(buku.getJudulBuku());
        pengarangField.setText(buku.getPengarang());
        
        String penerbit = buku.getPenerbit();
        switch(penerbit){
            case "Yudhistira" : yudhistiraRb.setSelected(true);break;
            case "Gramedia" : gramediaRb.setSelected(true);break;
            case "Airlangga" : airlanggaRb.setSelected(true);break;
            default:ygLainRb.setSelected(true);break;
        }
        tahunTerbitCb.setSelectedItem(String.valueOf(buku.getTahunTerbit()));
    }
    
    public void setBuku(Buku buku){
        this.buku = buku;
        showOldDataOf(buku);
    }
    
    private String getSelectedPenerbit(){
        if (yudhistiraRb.isSelected()){
            return "Yudhistira";
        }else if (gramediaRb.isSelected()){
            return "Gramedia";
        }else if(airlanggaRb.isSelected()){
            return"Airlangga";
        }else if (ygLainRb.isSelected()){
            return "Yang Lain";
        }else {
            return"";
        }
        
    }
    
    private boolean validateAllInput(){
        String judul = judulField.getText();
        if(judul.isEmpty()){
            showError("Judul buku masih kosong");
            return false;
        }
        String pengarang = pengarangField.getText();
        if(pengarang.isEmpty()){
            showError("Pengarang buku masih kosong");
            return false;
        }
        String penerbit = getSelectedPenerbit();
        if(pengarang.isEmpty()){
            showError("Penerbit belum dipilih");
            return false;
        }
        String tahunTerbit = tahunTerbitCb.getSelectedItem().toString();
        if(tahunTerbit.isEmpty()){
            showError("Tahun terbit belum ada yang dipilih");
            return false;
        }
        return true;
    }
    
    private void collectDataFor(Buku buku) {
        String judul = judulField.getText();
        String pengarang = pengarangField.getText();
        String penerbit = getSelectedPenerbit();
        String tahunTerbit = tahunTerbitCb.getSelectedItem().toString();
   
        buku.setJudulBuku(judul);
        buku.setPengarang(pengarang);
        buku.setPenerbit(penerbit);
        buku.setTahunTerbit(Integer.parseInt(tahunTerbit));
    }
    
    private void saveNewData() {
        buku = new Buku();
        collectDataFor(buku);
     
        BukuDatasource datasource = new BukuDatasource();
        try {
            datasource.save(buku);
            showSucceed("Data buku berhasil disimpan");
        } catch (SQLException e) {
            showError("Data buku gagal disimpan");
            e.printStackTrace();
        }
    }
    
    private void updateData(){
        collectDataFor(buku);
     
        BukuDatasource datasource = new BukuDatasource();
        try {
            datasource.update(buku);
            showSucceed("Data buku berhasil diperbaharui");
        } catch (SQLException e) {
            showError("Data buku gagal diperbaharui");
            e.printStackTrace();
        }
    }
    
    private void simpan(){
        if (!validateAllInput()) {
        return;
        }

        if (buku != null) {
            updateData();
        } else {
            saveNewData();
        }
    }
    //@Override
    public void etTitle(String title) {
        super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
    titleActivity.setText(title);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleActivity = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        judulField = new javax.swing.JTextField();
        pengarangField = new javax.swing.JTextField();
        tahunTerbitCb = new javax.swing.JComboBox<>();
        yudhistiraRb = new javax.swing.JRadioButton();
        airlanggaRb = new javax.swing.JRadioButton();
        gramediaRb = new javax.swing.JRadioButton();
        ygLainRb = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleActivity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleActivity.setText("Form Buku");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Judul");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Pengarang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Penerbit");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tahun Terbit");

        pengarangField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengarangFieldActionPerformed(evt);
            }
        });

        tahunTerbitCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2001", "2002", "2003", "2004" }));
        tahunTerbitCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunTerbitCbActionPerformed(evt);
            }
        });

        buttonGroup1.add(yudhistiraRb);
        yudhistiraRb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yudhistiraRb.setText("Yudhistira");
        yudhistiraRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yudhistiraRbActionPerformed(evt);
            }
        });

        buttonGroup1.add(airlanggaRb);
        airlanggaRb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        airlanggaRb.setText("Airlangga");

        buttonGroup1.add(gramediaRb);
        gramediaRb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gramediaRb.setText("Gramedia");
        gramediaRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gramediaRbActionPerformed(evt);
            }
        });

        buttonGroup1.add(ygLainRb);
        ygLainRb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ygLainRb.setText("Yang Lain");

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Batal");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tahunTerbitCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(titleActivity)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pengarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yudhistiraRb)
                                            .addComponent(airlanggaRb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ygLainRb)
                                            .addComponent(gramediaRb))))))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleActivity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pengarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yudhistiraRb)
                    .addComponent(gramediaRb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlanggaRb)
                    .addComponent(ygLainRb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tahunTerbitCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void yudhistiraRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yudhistiraRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yudhistiraRbActionPerformed

    private void gramediaRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gramediaRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gramediaRbActionPerformed

    private void tahunTerbitCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunTerbitCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunTerbitCbActionPerformed

    private void pengarangFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengarangFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengarangFieldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBukuActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton airlanggaRb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton gramediaRb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField judulField;
    private javax.swing.JTextField pengarangField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> tahunTerbitCb;
    private javax.swing.JLabel titleActivity;
    private javax.swing.JRadioButton ygLainRb;
    private javax.swing.JRadioButton yudhistiraRb;
    // End of variables declaration//GEN-END:variables
}
